//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SugerenciasServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SugerenciasEntities : DbContext
    {
        public SugerenciasEntities()
            : base("name=SugerenciasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acomulador> acomuladors { get; set; }
        public virtual DbSet<baseconocimiento> baseconocimientoes { get; set; }
        public virtual DbSet<palabra> palabras { get; set; }
        public virtual DbSet<TblUsuario> TblUsuarios { get; set; }
    }
}
